name 'puppet-ispconfig'
version '0.0.1'
author 'meth'
license 'GPLv2'
summary 'Puppet module to install ISPConfig in a LEMP environment'
description 'Puppet module to install ISPConfig in a LEMP environment'
project_page 'https://github.com/meth/puppet-ispconfig/'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/apt'
dependency 'puppetlabs/ntp'
dependency 'puppetlabs/mysql'
dependency 'thias/php'
dependency 'saz/pureftpd'
dependency 'camptocamp/openssl'
